apiVersion: apps/v1
kind: Deployment
metadata:
  name: nu-vooruit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nu-vooruit
  template:
    metadata:
      labels:
        app: nu-vooruit
    spec:
      containers:
        - name: nu-vooruit
          image: bitsenbytes/nu-vooruit:frontend_0.3
          ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nu-vooruit-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: nu-vooruit
      port: 80
  selector:
    app: nu-vooruit